FROM python:3.13.2-slim-bullseye AS builder

WORKDIR /app
COPY requirements.txt /app/
RUN pip install -r requirements.txt --target ./package


FROM scratch
ARG ENVIRONMENT=production
COPY --from=builder /app/package package

