FROM python:3.11-slim

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y curl unzip build-essential

ENV FLASK_APP=app
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_ENV=development
ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=TRUE

WORKDIR /app
COPY requirements-dev.txt .
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY app .

EXPOSE 8000

CMD ["flask", "run", "--debug", "--host=0.0.0.0", "--port=8000"]
